# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-18 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateTracking', '0002_candidate_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='sex',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
