# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-18 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateTracking', '0004_candidate_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
